### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by clintonjosephs** [gtekle/todo-list#2]
Hi @gtekle 👋  ,

You have done a tremendous job on your project so far, here are the highlights we identified:

✔️ Your project structure and how you literally added all sections from your javascript
✔️ Correct use of ES6
✔️ Enter button adds to-do items to the list
✔️ Styling is great
✔️ Generally your project struct is very nice.

Please find below a few things that can be improved upon
- The delete functionality does not work properly yet, It deletes more than one item when you click to delete 1 item from the list.
- Consider having more modules in different js files, this will make your classes more concise and readable
- Consider declaring the children of an element as a `const` above your functions so you would not have to reuse the index mapping over and over again, see below example.
              - Instead of saying li.children[0].children[1].classList.add("remove")
              - You can say const liChild = li.children[0].children[1];  liChild.classList.add("remove")

Your approach to the project is really organised! Kudos 😊 

Feel free to reach out if anything is not 100% clear.

**Comment by gtekle** [comment]
Hi @clintonjosephs

Thank you very much for the professionally crafted detailed feedback here. I can say it is for the first time in the morning sessions that I have got such well thought out and invaluable feedback.  :+1:  :+1: 

I will make sure that I address each point raised here.

thank you again :bow:

**Comment by clintonjosephs** [comment]
Thank you @gtekle for this acknowledgement!!! It means alot

**Comment by gtekle** [comment]
The delete functionality is implemented correctly
Code is refactored into modules and components
variables are used to hold repeating generated object manipulation and string manipulation properties
