### ISSUE TITLE
Uncleared input field on task submission

### ISSUE THREAD

**Issue by billionsjoel** [gtekle/todo-list#6]
1. When i add a task and click submit, the old (just entered task ) text remains in the input and its not cleared. I would suggest clearing the input field on task submission for good user experience.

2. I have also realised that the app-screenshot image on the readme.md is not showing. I would suggest that fix too. You have done a great job on the app. keep it up

<img width="815" alt="Screenshot 2022-01-16 at 20 21 24" src="https://user-images.githubusercontent.com/15736819/149670675-81a5e6ee-4742-47fd-88f0-e83f98574781.png">
.

**Comment by gtekle** [comment]
Hi @billionsjoel 
Thank you very much for taking the time to check it out and being kind enough to leave me a feedback that improves the project. 

That was a good catch. :+1:


I have fixed the 'uncleared input field' upon new task creation and I am working on the snapshot image that is not displayed in the README file for some reason.

[Update] I have fixed the issue of the snapshot image that was not displayed on the README file as well. I just forgot to add a directory name in the path. 

thanks again.  :bow:
